name: Обновление списка блог-постов

# Триггеры: пуш, расписание и кнопка Run workflow
on:
  push:
    branches:
      - main           # или ваша основная ветка
    paths:
      - README.md      # опционально — только при изменении README
  schedule:
    - cron: '0 * * * *' # каждый час в 0-ю минуту UTC (будет дополнительно)
  workflow_dispatch:    # ручной запуск на вкладке Actions

# Нужно, чтобы Action мог пушить правки в README
permissions:
  contents: write

jobs:
  update-blog-post-list:
    name: Вставить последние посты
    runs-on: ubuntu-latest

    steps:
      # 1) Клонируем репозиторий
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Вставляем блог-посты между маркерами
      - name: Обновить README
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/sarahokolo/"
          max_post_count: 5
          readme_path: ./README.md
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      # 3) (Необязательно) Логи, чтобы убедиться, что всё прошло
      - name: Show README diff
        run: |
          git diff README.md || echo "No changes"
